version: '3.7'

x-logging:
    &json-logging
    driver: json-file
    options:
        max-size: "1m"
        max-file: "3"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        TZ: 'Asia/Tokyo'
    image: custom.nginx
    container_name: nginx
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./envs/nginx/.env
    network_mode: service:wireguard
    volumes:
      - certs:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.template:/etc/nginx/template/default.template:ro
      - ./nginx/html:/var/www/html
    depends_on:
      - wireguard
    restart: always
    logging: *json-logging

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    env_file:
      - ./envs/wireguard/.env
    networks:
      - vpn
    ports:
      - 443:443
      - ${HOST_WIREGUARD_SERVERPORT:-51820}:51820/udp
    volumes:
      - /lib/modules:/lib/modules
      - ./wireguard:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
    logging: *json-logging

networks:
  vpn:
    name: vpn

volumes:
  certs:
    name: letsencrypt_cert
